//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI_Learning1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderLog
    {
        public int Id { get; set; }
        public int OrderId { get; set; }
        public string Status { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string EmployeeId { get; set; }
        public string CustomerId { get; set; }
    }
}
